name: 'tests Linux'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  linux:

    runs-on: ubuntu-20.04
    strategy:
      matrix:
        include:
          - backend: "all"
            run_tests_command: "./ngl-env tests"
          - backend: "opengles 2"
            run_tests_command: "MESA_GLES_VERSION_OVERRIDE=2.0 ./ngl-env tests --suite opengles"

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt -y update
        #
        # python3-venv is required to prevent the following issue:
        #     The virtual environment was not created successfully because ensurepip is not
        #     available.  On Debian/Ubuntu systems, you need to install the python3-venv
        #     package using the following command.
        #
        #         apt-get install python3-venv
        #
        sudo apt -y install libsdl2-dev python3-venv
        sudo apt -y install ffmpeg libavcodec-dev libavutil-dev libavformat-dev libavdevice-dev libavfilter-dev libswscale-dev libswresample-dev libpostproc-dev

    - name: Build
      run: |
        ./ngl-env build --buildtype debug --debug gl gpu_capture

    - name: Python import and dylib runtime test
      run: |
        . venv/bin/activate
        python -c "import pynodegl, pynodegl_utils"
        ngl-python -h

    - name: Run tests ${{matrix.backend}}
      run: |
        ${{matrix.run_tests_command}}

