name: 'tests Mac'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  macos:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        brew install python3 curl pkg-config sdl2 ffmpeg ninja
        # https://docs.brew.sh/Homebrew-and-Python
        pip3 install --upgrade pip
        # Install meson
        pip3 install meson

    - name: Build
      run: |
        make -j$(($(sysctl -n hw.logicalcpu)+1))

