name: 'tests MSVC'

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  msvc:

    runs-on: windows-latest
    env:
        VCPKG_TRIPLET: x64-windows
        VCPKG_INSTALL_PACKAGES: opengl-registry ffmpeg[ffmpeg,ffprobe] sdl2 spirv-cross
        VULKAN_SDK_VERSION: 1.2.162.1

    defaults:
      run:
        shell: pwsh

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get vcpkg cache key
        shell: bash
        id: get-vcpkg-cache-key
        run: |
          VCPKG_COMMIT_ID=$(git -C C:/vcpkg rev-parse HEAD)
          echo "::set-output name=key::$(echo $VCPKG_COMMIT_ID ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}} | md5sum | cut -f1 -d" ")"

      - name: Restore vcpkg binary cache archives
        id: restore_vcpkg_binary_cache
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ steps.get-vcpkg-cache-key.outputs.key }}

      - name: Install dependencies
        run: |
          pip.exe install meson
          iwr https://sdk.lunarg.com/sdk/download/${{env.VULKAN_SDK_VERSION}}/windows/VulkanSDK-${{env.VULKAN_SDK_VERSION}}-Installer.exe -OutFile VulkanSDK-${{env.VULKAN_SDK_VERSION}}-Installer.exe && `
          ./VulkanSDK-${{env.VULKAN_SDK_VERSION}}-Installer.exe /S
          cd C:\vcpkg
          .\vcpkg.exe install --triplet ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}}

      - name: Build
        continue-on-error: true
        run: |
          .\scripts\msvc-env.ps1
          $env:VULKAN_SDK='C:\VulkanSDK\${{env.VULKAN_SDK_VERSION}}'
          python.exe .\configure.py --buildtype debug --debug gl gpu_capture --enable-ngfx-backend
          nmake

      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: nodegl-msvc-build-logs
          path: |
            builddir/**/*.txt
            builddir/**/*.cmake
            builddir/**/*.log
            builddir/Makefile
