name: 'tests Windows MSVC'

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  msvc:

    runs-on: windows-latest
    env:
        VCPKG_TRIPLET: x64-windows
        VCPKG_INSTALL_PACKAGES: pthreads opengl-registry ffmpeg[ffmpeg,ffprobe] sdl2

    defaults:
      run:
        shell: wsl-bash {0}

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04
          wsl-shell-command: bash --noprofile --norc -x

      - uses: actions/checkout@v2

      - name: Get vcpkg cache key
        id: get-vcpkg-cache-key
        run: |
          VCPKG_COMMIT_ID=$(cd /mnt/c/vcpkg && git rev-parse HEAD)
          echo "::set-output name=key::$(echo $VCPKG_COMMIT_ID ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}} | /usr/bin/md5sum | /bin/cut -f1 -d" ")"

      - name: Restore vcpkg binary cache archives
        id: restore_vcpkg_binary_cache
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ steps.get-vcpkg-cache-key.outputs.key }}

      - name: Install dependencies
        run: |
          sudo apt -y update
          sudo apt -y install build-essential unzip wget python3-venv p7zip-full
          pip.exe install meson
          cd /mnt/c/vcpkg
          ./vcpkg.exe install --triplet ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}}
          # TODO: remove vcpkg.exe integrate install
          ./vcpkg.exe integrate install

      - name: Build
        run: |
          cd /mnt/c
          # Workaround for meson issue #8329
          # Currently meson requires the project to be on the same drive as dependencies
          cp -Rf /mnt/d/a/gopro-lib-node.gl/gopro-lib-node.gl .
          cd gopro-lib-node.gl
          # Save the following commands to a variable
          read -r -d '' COMMANDS << EOM
          export VCPKG_DIR='C:\vcpkg'
          source build_scripts/windows/setenv.sh
          bash build_scripts/windows/patch_pkg_config_files.sh
          make DEBUG_GPU_CAPTURE=yes
          EOM
          tmpfile=$(mktemp)
          echo "$COMMANDS" > $tmpfile
          # Execute the commands in an msvc dev environment
          bash build_scripts/windows/start_msvc_env.sh $tmpfile

