name: 'tests MSVC'

on:
  push:
    branches:
      - 'master'
  pull_request:
  schedule:
      - cron: "0 0 * * 6"  # Run every Saturday at midnight

jobs:
  msvc:

    runs-on: windows-latest
    env:
        VCPKG_TRIPLET: x64-windows
        VCPKG_INSTALL_PACKAGES: opengl-registry ffmpeg[ffmpeg,ffprobe] sdl2

    defaults:
      run:
        shell: powershell

    steps:
      - uses: Vampire/setup-wsl@v1
        with:
          distribution: Ubuntu-20.04

      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Get vcpkg cache key
        shell: wsl-bash {0}
        id: get-vcpkg-cache-key
        run: |
          VCPKG_COMMIT_ID=$(cd /mnt/c/vcpkg && git rev-parse HEAD)
          echo "::set-output name=key::$(echo $VCPKG_COMMIT_ID ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}} | md5sum | cut -f1 -d" ")"

      - name: Restore vcpkg binary cache archives
        id: restore_vcpkg_binary_cache
        uses: actions/cache@v2
        with:
          path: C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ steps.get-vcpkg-cache-key.outputs.key }}

      - name: Install dependencies
        run: |
          cd C:\vcpkg
          .\vcpkg.exe install --triplet ${{env.VCPKG_TRIPLET}} ${{env.VCPKG_INSTALL_PACKAGES}}

      - name: Build
        run: |
          .\scripts\msvc-env.ps1
          python.exe .\ngl-env clean --venv
          python.exe .\ngl-env build --debug gpu_capture
