name: 'tests MinGW'

on:
  push:
    branches:
      - 'master'
  pull_request:

jobs:
  mingw:

    runs-on: windows-latest

    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: actions/checkout@v2

      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64 # Start a 64 bit Mingw environment
          update: true

      - name: Install dependencies
        run: |
          pacman -S --noconfirm --needed git make
          pacman -S --noconfirm --needed mingw-w64-x86_64-{toolchain,ffmpeg,python}
          pacman -S --noconfirm --needed mingw-w64-x86_64-python3-{pillow,pip}
          pacman -S --noconfirm --needed mingw-w64-x86_64-meson
          pacman -S --noconfirm --needed mingw-w64-x86_64-shaderc

      - name: Install Vulkan SDK
        shell: powershell
        run: |
          $env:CHERE_INVOKING = 'yes'  # Preserve the current working directory
          C:\msys64\usr\bin\bash -lc "wget https://sdk.lunarg.com/sdk/download/1.2.162.1/windows/VulkanSDK-1.2.162.1-Installer.exe"
          ./VulkanSDK-1.2.162.1-Installer.exe /S

      - name: Build
        run: |
          make -j$(($(nproc)+1)) TARGET_OS=MinGW-w64
